### ISSUE TITLE
IDiagnostic.SetFirewallConfiguration() missing brace in API declaration.

### ISSUE THREAD

**Issue by ptr727** [loopj/aiovantage#97]
### Checklist

- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Looks like a missing [closing brace](https://github.com/loopj/aiovantage/blame/main/docs/aci_service.md#L113), I can guess where it goes, but I don't know the source of the API declaration, so leaving it to you to fix.

`IDiagnostic.SetFirewallConfiguration(OpenPorts: {TCP: List[int], UDP: List[int], ICMP: bool)`

Maybe `IDiagnostic.SetFirewallConfiguration(OpenPorts: {TCP: List[int], UDP: List[int], ICMP: bool})`

Btw, where is this documented?

### Reproduction steps

Noticed in VSCode warning about a missing brace.

**Comment by loopj** [comment]
Fixed in 611d0ebc8f9ac9fb833ea96c3ed8564805edd749

> Btw, where is this documented?

This is not documented *anywhere*, I had to reverse engineer them all!
