### ISSUE TITLE
Child loads for LVRS8-DIN station are not associated with station

### ISSUE THREAD

**Issue by ptr727** [loopj/aiovantage#99]
### Checklist

- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

LVRS8-DIN is detected (thank you), but parent (controller) to child (load) relationship is not reported in HA, i.e. station has no loads and relay loads have no parent.
  
In contrast DualRelayStation (keypad) and ModuleGen2 (SDM12) does maintain the parent/controller - child/loads relationship in HA.

On reviewing the XML, the LVRS8-DIN and its loads are reported as parent child, just like the DualRelayStation and ModuleGen2.  
But, the DualRelayStation has a blackbox parent, regardless, the loads of the DualRelayStation does point directly to the DualRelayStation as parent, same with ModuleGen2.

### Reproduction steps

- Add system with LVRS8-DIN and loads to HA.
- Observe that LVRS8-DIN and loads are detected.
- But that there is no parent/child relationship reported in HA.

XML and dump_system.py logs attached for reference.

[dump_system.zip](https://github.com/loopj/aiovantage/files/14973544/dump_system.zip)
[DC46.zip](https://github.com/loopj/aiovantage/files/14973903/DC46.zip)

**Comment by loopj** [comment]
Should be fixed in latest version of https://github.com/loopj/home-assistant-vantage with the introduction of BackBox support
